### ISSUE TITLE
Persian / Arabic fonts

### ISSUE THREAD

**Issue by shahabsiavash** [EagerApps/GoogleFonts#4]
Hi,

Google Fonts has almost 16 Arabic fonts and since the Latin fonts don't have Arabic glyhps, so it would be great if it had a language tab for non-English users.

+ A custom font upload would be great too. (@font-face generator)

Thanks for your great apps,

**Comment by GirlBossRush** [comment]
Arabic fonts added in 6e1921d7aa5bd5b4559f95ee8f53ee14fc75e5e2
